Autos/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('lista_autos/', views.lista_autos, name="lista_autos"),
    path('lista_motos/', views.lista_moto, name="lista_motos"),
    path('detalle_moto/<int:id>/', views.detalle_moto, name="detalle_moto"),
    path('detalle_auto/<int:id>/', views.detalle_auto, name="detalle_auto"),
    path('buscar_auto/', views.busquedaAuto, name="buscar_auto")
]

Inicio/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
   path("", views.inicio, name='inicio'),

    
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Inicio.urls')),
    path('inicio/', include(('Inicio.urls','Inicio'), namespace='inicio')),
    path('autos/', include(('Autos.urls','Autos'), namespace='autos'))
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.FONDO_URL, document_root=settings.MEDIA_FONDO)

Autos/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
# transmision = (('manual', 'Manual'), ('automatico', 'Automatico'))

class Auto(models.Model):
    Marca = models.CharField(max_length=200)
    Modelo = models.CharField(max_length=200)
    Año = models.IntegerField(max_length=4)
    Color = models.CharField(max_length=30)
    Placa = models.CharField(max_length=15)
    Cilindrada = models.IntegerField(max_length=10)
    Transmision = models.CharField(max_length=30)
    Precio = models.DecimalField(max_digits=20, decimal_places=2)
    Foto = models.ImageField(upload_to='fotos')

class Moto(models.Model):
    Marca = models.CharField(max_length=200)
    Modelo = models.CharField(max_length=200)
    Año = models.IntegerField(max_length=4)
    Color = models.CharField(max_length=30)
    Placa = models.CharField(max_length=15)
    Cilindrada = models.IntegerField(max_length=10)
    Precio = models.DecimalField(max_digits=20, decimal_places=2)
    Foto = models.ImageField(upload_to='fotos')
    

Inicio/models.py
from django.db import models

# Create your models here.

Autos/forms.py
from django import forms
from .models import Auto, Moto
from Autos import models

class AutosForm(forms.ModelForm):
    class Meta:
        model = Auto
        fields = '__all__'

class MotoForm(forms.ModelForm):
    class Meta:
        model = Moto
        fields = '__all__'

Inicio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name' : 'Nombres',
            'last_name' : 'Apellidos',
            'password1' : 'Contraseña',
            'password2' : 'Confirmar Contraseña'

        } 
        help_texts = {k:"" for k in fields           
        }

Autos/views.py
from django.core import paginator
from django.core.checks import messages
from django.http.response import Http404
from django.shortcuts import render, redirect
from .forms import AutosForm, MotoForm
from Autos.models import*
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import Http404
# Create your views here.

def lista_autos(request):
    busqueda = request.GET.get("buscar")
    autos = Auto.objects.all()

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(autos, 3)
        autos = paginator.page(page)

    except:
        raise Http404

    if busqueda:
        autos = Auto.objects.filter(
            Q(Marca__icontains = busqueda) | 
            Q(Modelo__icontains = busqueda)
        ).distinct()
    return render(request, 'carros/lista_autos.html', {"entity":autos, "paginator" : paginator})            

# View Motos

def lista_moto(request):
    busqueda = request.GET.get("buscar")
    motos = Moto.objects.all()

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(motos, 3)
        motos = paginator.page(page)

    except:
        raise Http404

    if busqueda:
        motos = Moto.objects.filter(
            Q(Marca__icontains = busqueda) | 
            Q(Modelo__icontains = busqueda)
        ).distinct()
    return render(request, 'carros/lista_motos.html', {"entity":motos, "paginator": paginator})
  
def detalle_moto(request, id):
    motos = Moto.objects.filter(id = id)
    return render(request, 'carros/detalle_motos.html', {"motos":motos})

def detalle_auto(request, id):
    autos = Auto.objects.filter(id = id)
    return render(request, 'carros/detalle_auto.html', {"autos":autos})

def busquedaAuto(request):
    busqueda = request.GET.get("buscar")
    autos = Auto.objects.all()
    if busqueda:
        autos = Auto.objects.filter(
            Q(Marca__icontains = busqueda) | 
            Q(Modelo__icontains = busqueda)
        ).distinct()
    return render(request, 'carros/lista_autos.html', {'autos' : autos})

Inicio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import RegistroForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from Autos.models import Auto, Moto

def inicio(request):
    return render(request, "login/inicio.html", {"autos":Auto.objects.all , "motos":Moto.objects.all})

templates/carros/detalle_auto.html
{% extends 'login/base.html' %}
{% block titulo %} Detalles {% endblock titulo%}


{% block contenido %}

<div class="container">
  <div class="jumbotron mt-4">
    {% for a in autos %}  
    <center> <h1 class="font-weight-bold center">{{a.Marca}} {{a.Modelo}}</h1> </center>
    <div class="row">
      <div class="col-md-7">
        <center><img src={{a.Foto.url}}  width="454px" height="312" style="border: 2px outset; color: orange;"/></span></center>

      </div>
      <div class="col-md-5">
        <div class="container">
          <h3>Detalles</h3>
          <p>Marca: {{a.Marca}}</p>
          <p>Modelo: {{a.Modelo}}</p>
          <p>Año: {{a.Año}}</p>
          <p>Precio: ${{a.Precio}}</p>
          {% endfor %}
        </div>

      </div>
    </div>
      <br><center><h5>¿Quieres cotizar este Auto?</h5></center><br>
      <center><a href="https://api.whatsapp.com/send?phone=0997778422&text=Hola, Nececito mas informacion!" class="btn btn-primary" target="_blank">Envianos un mensaje al WhatsApp</a></center>
  </div>
</div>


  <script>
     document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });
  </script>


{% endblock contenido %}

templates/carros/detalle_motos.html
{% extends 'login/base.html' %}
{% block titulo %} Detalles {% endblock titulo%}


{% block contenido %}

<div class="container">
  <div class="jumbotron mt-4">
    {% for m in motos %}  
    <center> <h1 class="font-weight-bold center">{{m.Marca}} {{m.Modelo}}</h1> </center>
    <div class="row">
      <div class="col-md-7">
        <center><img src={{m.Foto.url}}  width="454px" height="312" style="border: 2px outset; color: orange;"/></span></center>

      </div>
      <div class="col-md-5">
        <div class="container">
          <h3>Detalles</h3>
          <p>Marca: {{m.Marca}}</p>
          <p>Modelo: {{m.Modelo}}</p>
          <p>Año: {{m.Año}}</p>
          <p>Precio: ${{m.Precio}}</p>
          {% endfor %}
        </div>

      </div>
    </div>
      <br><center><h5>¿Quieres cotizar esta moto?</h5></center><br>
      <center><a href="https://api.whatsapp.com/send?phone=0997778422&text=Hola, Nececito mas informacion!" class="btn btn-primary" target="_blank">Envianos un mensaje al WhatsApp</a></center>
  </div>
</div>


  <script>
     document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });
  </script>


{% endblock contenido %}

templates/carros/lista_autos.html
{% extends 'login/base.html' %}
{% block titulo %} Autos {% endblock titulo%}


{% block buscador %}

<nav class="navbar navbar-expand-lg navbar-light bg-light"></nav>
<form class="form-inline my-2 my-lg-0" method="GET">
  {% csrf_token %}
  <input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Buscar" name="buscar" value="{{ request.GET.buscar }}">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
</form>
</nav>
{% endblock buscador%}
{% block contenido %}
    <div class="jumbotron p-3 mb-2 bg-dark text-black mb-auto">
      <div class="container">
        <div class="row">
          {% for a in entity %}

          <div class="col-md-4">
            <div class="card" style="width: 18rem; margin-top: 5%;">
              <img class="card-img-top" src="{{a.Foto.url}}" alt="Card image cap" style="width: 285px; height: 200px;">
              <div class="card-body">
                <h5 class="card-title">{{a.Marca}} {{a.Modelo}}</h5>
                <a href="{% url 'autos:detalle_auto' a.id %}" class="btn btn-primary">Ver mas detalles</a>

              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        <div style="margin-top: 5%;">
          {% include 'carros/paginator.html' %}
        </div>
      </div>
    </div>
  


  <script>
     document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });
  </script>

{% endblock contenido %}

templates/carros/lista_motos.html
{% extends 'login/base.html' %}
{% block titulo %} Motos {% endblock titulo%}


{% block buscador %}

<nav class="navbar navbar-expand-lg navbar-light bg-light"></nav>
<form class="form-inline my-2 my-lg-0" method="GET">
  {% csrf_token %}
  <input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Buscar" name="buscar" value="{{ request.GET.buscar }}">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
</form>
</nav>
{% endblock buscador%}
{% block contenido %}
      <div class="container">
        <div class="row">
          {% for m in entity %}

          <div class="col-md-4">
            <div class="card" style="width: 18rem; margin-top: 5%;">
              <img class="card-img-top" src="{{m.Foto.url}}" alt="Card image cap" style="width: 285px; height: 200px;">
              <div class="card-body">
                <h5 class="card-title">{{m.Marca}} {{m.Modelo}}</h5>
                <a href="{% url 'autos:detalle_moto' m.id %}" class="btn btn-primary">Ver mas detalles</a>

              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        <div style="margin-top: 5%;">
          {% include 'carros/paginator.html' %}
        </div>
      </div>


{% endblock contenido %}

templates/carros/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Import Google Icon Font-->
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
    
    <title>{% block titulo %} Inicio {% endblock titulo%}</title>

   
      
</head>
<style>
  
</style>
<body class="bg-dark text-black m-0">

  <nav class="navbar navbar-expand-lg navbar-light bg-light m-0">
        <div class="container">
        <a class="navbar-brand" href="{% url 'inicio' %}">JISA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto ">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Autos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'autos:lista_autos' %}">Lista de Autos</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Motos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'autos:lista_motos' %}">Lista de Motos</a>
              </div>
            </li>
          </ul>
          {% block buscador %}
          {% endblock buscador%}
        </div>
      </div>
    </nav>
    {% block contenido %}
    {% endblock contenido %}

 <!-- Compiled and minified JavaScript -->
 <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

 <script>
  
  document.addEventListener('DOMContentLoaded', function() {
    // var elems = document.querySelectorAll('.sidenav');
    // var instances = M.Sidenav.init(elems);
    M.AutoInit();
  });
    
  </script>
            
</body>
</html>

templates/login/inicio.html
{% extends 'login/base.html' %}
{% block titulo %} Inicio {% endblock titulo%}

{% block contenido %}

<div class="jumbotron p-3 mb-2 bg-dark text-white mb-auto">
  <center>
    <h1 class="font-weight-bold center">Bienvenido a JISA</h1>
    <h2 class="font-italic">Donde todo lo moderno esta al alcance de tus manos</h2>
  </center>

</div>

<div class="jumbotron mb-auto">
  <div class="row">
    <div class="col-md-5">
      <div class="container mt-4">
        <h1 class="font-weight-bold center">Automoviles</h1>
      <p class="font-italic">
        En este lugar encontraras los automoviles mas actuales del Mundo.
        Para mas informacion dirigete a la seccion lista o dale click a la imagen.
      </p>
      </div>
    </div>
    <div class="col-md-7">
      <a href="{% url 'autos:lista_autos' %}">
      <div class="carousel slide" id="demo-carousel" data-ride="carousel" style="margin-top: 5%;">
        <div class="carousel-inner" role="listbox" >
          {% for a in autos %}
            {% if forloop.first %}
              <div class="carousel-item active" >
            {% else %}
              <div class="carousel-item" >
            {% endif %}
              {% if a.Foto %}
                <img class="col d-flex justify-content-center" src='{{ a.Foto.url }}' alt=""  style="width: 100%; height: 65%; margin: auto;">
              {% endif %}
                <div class="carousel-caption">
                  <p>{{ a.Marca }} {{ a.Modelo }}</p>
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
      </div>
      </a>
    </div>
  
  </div>
</div>



<div class="jumbotron p-3 mb-2 bg-dark text-white mb-auto">
  <div class="row">
    <div class="col-md-5">
      <div class="container mt-4">
        <h1 class="font-weight-bold center">Motocicletas</h1>
      <p class="font-italic">
        En este lugar encontraras las mejores motocicletas del mercado y las mas actuales del Mundo.
        Para mas informacion dirigete a la seccion lista o dale click a la imagen.
      </p>
      </div>
    </div>
    <div class="col-md-7">
      <a href="{% url 'autos:lista_motos' %}">
      <div class="carousel slide" id="demo-carousell" data-ride="carousel" style="margin-top: 5%; " >
        <div class="carousel-inner" role="listbox" >
          {% for m in motos %}
            {% if forloop.first %}
              <div class="carousel-item active" >
            {% else %}
              <div class="carousel-item" >
            {% endif %}
              {% if m.Foto %}
                <img class="col d-flex justify-content-center" src='{{ m.Foto.url }}' alt=""  style="width: 100%; height: 65%; margin: auto; border: 50px;">
              {% endif %}
                <div class="carousel-caption">
                  <p>{{ m.Marca }} {{ m.Modelo }}</p>
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
      </div>
      </a>
    </div>
  
  </div>
</div>


<script type="text/javascript">
$('.carousel').carousel({
  interval: 100
})

</script>
  

{% endblock contenido %}